version: "3.8"
services:
  frontend:
    build:
      context: ./nginx
      additional_contexts:
        web: ../../apps/web/
        sect: ../../apps/strategyExecutorContextTypes/
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost/api}
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      additional_contexts:
        api: ../../apps/api/
        sect: ../../apps/strategyExecutorContextTypes/
    container_name: backend
    environment:
      MONGODB_URI: mongodb://${BACKEND_USER:-backend}:${BACKEND_PASSWORD:-pass}@mongodb:27017/${MONGODB_INITDB_DATABASE:-backend}
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-root}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-pass}
      MONGODB_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE:-backend}
      BACKEND_USER: ${BACKEND_USER:-backend}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD:-pass}
    ports:
      - 27017:27017
    volumes:
      # - ./mongoDb/data:/data/db
      - ./mongoDb/initiate.js:/docker-entrypoint-initdb.d/initiate.js
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-pass}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ports:
      - 8080:8081
    depends_on:
      - mongodb
