version: "3.8"
services:
  frontend:
    extends:
      file: ./docker-compose.yml
      service: frontend
    build:
      context: ./nginx
      dockerfile: https.Dockerfile
      additional_contexts:
        web: ../../apps/web/
        sect: ../../apps/strategyExecutorContextTypes/
      args:
        DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://localhost/api}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/snippets:/etc/nginx/snippets
    depends_on:
      - backend
  backend:
    extends:
      file: ./docker-compose.yml
      service: backend
  mongodb:
    extends:
      file: ./docker-compose.yml
      service: mongodb
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ports:
      - 8080:8081
    depends_on:
      - mongodb
  # sonarqube:
  #   image: sonarqube:10-community
  #   # volumes:
  #   #   - ./sonarqube/extensions:/opt/sonarqube/extensions
  #   #   - ./sonarqube/logs:/opt/sonarqube/logs
  #   #   - ./sonarqube/data:/opt/sonarqube/data
  #   ports:
  #     - 9000:9000
