#!/bin/sh

# Stop execution instantly while having a non-zero status.
set -e

echo "[INFO] Pre-commit hook of Web project"

changeNum=$(git diff --staged --name-only -- apps/web | wc -l)

if [ $changeNum != 0 ]; then
    CURRENT_DIR=$(dirname "$0")
    cd $CURRENT_DIR/../

    npm run lint
    npm run prettier
    npm run test:u
    
    echo "[INFO] Pre-commit hook of Web project done"
else
    echo "[INFO] Skipped because no changes from this directory were committed"
fi